env_module: "policy.envs.randomplay_env:RandomPlayEnv"
env_name: "RandomPlayEnv"
num_parallel_test: 1

model_type: 'randomplay'

max_timestep: 500
max_timestep_test: 500
frame_skip: 1

#text: ['sidestep', 'forward', 'backward', 'stand still',',']
